/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Datos;

import javax.swing.JFrame;

/**
 *
 * @author Dell-Insp15
 */

//definicion de un objeto tipo persona  referencia a la pregunta --¿Que es?
public class Persona {
    //caracteristicas de l objeto responde a la pregunta --¿Como es?
    String cedula;
    String nombre;
    String apellido1;
    String apellido2;
    String telefono;
    String correo;
    
    //constructor vacio, para apartar la memoria del registro
    public Persona() {
    }

    public Persona(String cedula, String nombre, String apellido1, String apellido2, String telefono, String correo) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.telefono = telefono;
        this.correo = correo;
    }

    //metodos de las acciones - SET(establecer) y GET(obtener)  -- utilizar metodos SETTER y GETTER
    //metodo get/GETTER

    public String getCedula() {
        return cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido1() {
        return apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getApellido2() {
        return apellido2;
    }
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnEspecie = new javax.swing.JButton();
        btnRaza = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnAnimal = new javax.swing.JButton();
        lblLogo1 = new javax.swing.JLabel();
        btnReceta = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        pblContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1800, 1640));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(53, 11, 13));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEspecie.setBackground(new java.awt.Color(255, 154, 22));
        btnEspecie.setFont(new java.awt.Font("Racer", 1, 18)); // NOI18N
        btnEspecie.setForeground(new java.awt.Color(255, 255, 255));
        btnEspecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Especie32x32.png"))); // NOI18N
        btnEspecie.setText("REGISTRO DE ESPECIES");
        btnEspecie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEspecie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecieActionPerformed(evt);
            }
        });
        pnlMenu.add(btnEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 240, 30));

        btnRaza.setBackground(new java.awt.Color(255, 154, 22));
        btnRaza.setFont(new java.awt.Font("Racer", 1, 18)); // NOI18N
        btnRaza.setForeground(new java.awt.Color(255, 255, 255));
        btnRaza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Raza32x32.png"))); // NOI18N
        btnRaza.setText("REGISTRO DE RAZAS");
        btnRaza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRaza.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRazaActionPerformed(evt);
            }
        });
        pnlMenu.add(btnRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, 30));

        btnCliente.setBackground(new java.awt.Color(255, 154, 22));
        btnCliente.setFont(new java.awt.Font("Racer", 1, 18)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente.png"))); // NOI18N
        btnCliente.setText("REGISTRO DE CLIENTES");
        btnCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        pnlMenu.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 240, 30));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P.png"))); // NOI18N
        pnlMenu.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        lblMenu.setFont(new java.awt.Font("Racer", 0, 24)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setText("MENU PRINCIPAL");
        pnlMenu.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 20));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 154, 22));
        btnCerrarSesion.setFont(new java.awt.Font("Racer", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/emblem-nowrite.png"))); // NOI18N
        btnCerrarSesion.setText("  CERRAR SESION");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlMenu.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 240, 30));

        btnReportes.setBackground(new java.awt.Color(255, 154, 22));
        btnReportes.setFont(new java.awt.Font("Racer", 1, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/display 22x22.png"))); // NOI18N
        btnReportes.setText("  REPORTES");
        btnReportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 240, 30));

        btnAnimal.setBackground(new java.awt.Color(255, 154, 22));
        btnAnimal.setFont(new java.awt.Font("Racer", 1, 18)); // NOI18N
        btnAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Animal.png"))); // NOI18N
        btnAnimal.setText("REGISTRO DE ANIMALES");
        btnAnimal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAnimal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalActionPerformed(evt);
            }
        });
        pnlMenu.add(btnAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 240, 30));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Happy.png"))); // NOI18N
        pnlMenu.add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        btnReceta.setBackground(new java.awt.Color(255, 154, 22));
        btnReceta.setFont(new java.awt.Font("Racer", 1, 18)); // NOI18N
        btnReceta.setForeground(new java.awt.Color(255, 255, 255));
        btnReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegRecetas.png"))); // NOI18N
        btnReceta.setText("  REGISTRO RECETAS");
        btnReceta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReceta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecetaActionPerformed(evt);
            }
        });
        pnlMenu.add(btnReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 240, 30));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 640));

        pnlTitulo.setBackground(new java.awt.Color(53, 11, 13));
        pnlTitulo.setForeground(new java.awt.Color(53, 11, 13));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Race Sport", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("HAPPY DOGS");
        pnlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 410, 90));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/01- Cerrar 32x32.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        pnlTitulo.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/03- Minimizar 32x32.png"))); // NOI18N
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMinimizarMousePressed(evt);
            }
        });
        pnlTitulo.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/02- Maximizar 32x32.png"))); // NOI18N
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMaximizarMousePressed(evt);
            }
        });
        pnlTitulo.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        getContentPane().add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 90));

        pblContenedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pblContenedor.setMaximumSize(new java.awt.Dimension(800, 800));
        pblContenedor.setPreferredSize(new java.awt.Dimension(650, 590));
        getContentPane().add(pblContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 540, 550));

        pack();
    }// </editor-fold>                        

    private void btnEspecieActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        FrmRegEspecies regEspecie = new FrmRegEspecies();
        regEspecie.setLocationRelativeTo(null);
        regEspecie.setVisible(true);
    }                                          

    private void btnRazaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        FrmRegRazas regRaza = new FrmRegRazas();
        regRaza.setLocationRelativeTo(null);
        regRaza.setVisible(true);
    }                                       

    private void btnAnimalActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        PnlClienteDos cli= new PnlClienteDos();
        cli.setSize(650,590);
        cli.setLocation(0,0);
    
 
        pblContenedor.removeAll();
        pblContenedor.add(cli);
        pblContenedor.revalidate();
        pblContenedor.repaint();
    }                                          

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        System.exit(0);
    }                                      

    private void btnMinimizarMousePressed(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        JFrame frame1 = new JFrame ("Ventana de ejemplo");
        frame1.setSize(400,300);
        frame1.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame1.setVisible(true);
        frame1.setState (JFrame.ICONIFIED);
    }                                         

    private void btnMaximizarMousePressed(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:

        this.setExtendedState(this.MAXIMIZED_BOTH);
    }                                         

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        this.hide();
        FrmLogin loginFrom = new FrmLogin();
        loginFrom.show();
    }                                               

    private void btnReportesActionPerformed(java.awt.event.ActionEvent ev
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }
    
    
    
    
}
